
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      ollama serve & 
      sleep 5 &&
      ollama pull llama3.2 && ollama pull mxbai-embed-large &&
      tail -f /dev/null"
      # Dòng 'tail -f /dev/null' giữ container chạy mãi mãi
      # Bạn có thể thay llama3:8b bằng mô hình mong muốn

  chatbot-app:
    build: ./chatbot_server_dev
    container_name: my-python-app
    ports:
      - "8502:8502"
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped
  
  admin-app:
    build: ./chatbot_admin
    container_name: my-python-admin-app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  ollama:
  qdrant_data:
